### ISSUE TITLE
Logarithmic frequency scale

### ISSUE THREAD

**Issue by unfa** [alexkay/spek#80] opened 2015-01-12 22:24 UTC
I really like how Spek draw it's spectrograms, however sometimes (for musical purposes) it's useful to be able to use a logarithmic scale instead of a linear one.

With the linear scale (what I see now in Spek) the medium and low frequencies are cluttered and hardly readable, while the high frequencies occupy 90% of the spectrogram's space providing a lot of superfluous information to the user.

I'd greatly appreciated a possiblity to switch the frequency scale that Spek uses for it's work :)

**Comment by alexkay** [comment] 2015-01-12 22:26
Duplicate of #11

**Closed by alexkay** 2015-01-12 22:26 UTC
