### ISSUE TITLE
Use an exponential frequency 'curve' rather than a linear one

### ISSUE THREAD

**Issue by SkyyySi** [alexkay/spek#215] opened 2021-11-22 14:58 UTC
Our hearing is not linear. It would be nice if we could get an exponential frequency curve, i.e. bottom frequencies are shown bigger than top ones. This would make spek show the frequencies as we hear them. Idealy, that could be toggled.

I'd be surprised if anyone's still working on this project though.

**Comment by danadam** [comment] 2021-12-13 05:35
duplicate of #11

**Closed** 2022-01-23 17:28 UTC
