### ISSUE TITLE
Feature Request: horizontal scrolling

### ISSUE THREAD

**Issue by daniel-samson** [alexkay/spek#93] opened 2016-03-27 16:15 UTC
I can't seem to scroll past the width of my window. 

Everything else seems to work. Good Job!

> My System:
> Ubuntu 15.10 64-bit
> Intel® Core™ i5 CPU 760 @ 2.80GHz × 4 
> 7.8 GiB
>

**Comment by alexkay** [comment] 2016-03-27 21:13
Duplicate of #3

**Closed by alexkay** 2016-03-27 21:13 UTC
