### ISSUE TITLE
Doesn't work in macOS Catalina

### ISSUE THREAD

**Issue by jpsalap** [alexkay/spek#187] opened 2020-03-15 23:34 UTC
Because of the macOS transition from 32bits to 64bits this app is not optimized. Hope this can be solved soon.

**Comment by neonUneon** [comment] 2020-03-18 22:13
The issue below about 64-bit has a working link, have to bypass security check in System Preferences->Security & Privacy.

https://github.com/withmorten/spek-alternative/releases

**Comment by fredOnGitHub** [comment] 2020-04-16 10:36
Hello,
i confirm. The pig logo is crossed out

**Comment by mattpopovich** [comment] 2020-08-24 05:59
This is a duplicate of #181. Recommending to close it.

**Comment by alexkay** [comment] 2023-02-06 21:52
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5

**Closed by alexkay** 2023-02-06 21:52 UTC
