### ISSUE TITLE
Generate and export graphic via command line

### ISSUE THREAD

**Issue by bardware** [alexkay/spek#124] opened 2016-12-23 21:34 UTC
I just stumbled upon a [project](http://www.gemmantics.com/spectrograms-in-c-with-libav-ffmpeg-libpng-and-sphinx/) that used FFMPEG a couple years back to analyze audio files.  It generates graphics using libpng. I didn't ry to compile -- too complicate.

**Comment by alexkay** [comment] 2016-12-27 23:16
Dupe of #9

**Closed by alexkay** 2016-12-27 23:16 UTC
