### ISSUE TITLE
Spek: Instant save to file.

### ISSUE THREAD

**Issue by robertmassaioli** [alexkay/spek#84] opened 2015-03-22 22:17 UTC
It would be really great if I could pass Spek options on the command line to instantly save its results into an image file. Instead of needing to open the app up every time and save the file by clicking a button. That way I could get images of hundreds of audio files with a single shell script run. That would be more than excellent.

**Comment by alexkay** [comment] 2015-03-22 23:20
Duplicate of #9

**Closed by alexkay** 2015-03-22 23:20 UTC
