### ISSUE TITLE
Stoped Working on macOS Sierra

### ISSUE THREAD

**Issue by Cap8X** [alexkay/spek#119] opened 2016-10-05 08:14 UTC
it stoped working after an official update to macOS Sierra ver. 10.12 on Mac.
crashes upon launching the app.
thanks.

**Comment by d1rtydutch** [comment] 2016-10-05 14:05
Yea seems they've known about it since beta but still have yet to fix it even after it's full release

**Comment by hanhpho** [comment] 2016-10-08 07:57
Sit tight, @alexkay is fixing it https://github.com/alexkay/spek/issues/107#issuecomment-249627485

**Comment by Cap8X** [comment] 2016-10-11 18:34
thanks. i'll be checking here if someone fixes is please post something here.

**Comment by TempSpas** [comment] 2016-10-16 16:32
Any update on this? It's been a few weeks since the update and I'd really like to start using Spek again.

**Comment by shigg1120** [comment] 2016-10-24 01:54
+1

**Comment by nguyenducphu** [comment] 2016-10-27 03:45
Same here. Please upgrade. I love this app.

**Comment by DennisSchwartz** [comment] 2016-10-27 21:55
And here! Love the app, I'd help out if my C++ was any better ;)

**Comment by matic13** [comment] 2016-10-29 11:20
+1. Please add support for macOS Sierra. Thanks!

**Comment by AxFx** [comment] 2016-10-30 13:54
@alexkay Any updates on this?

**Comment by DachengZ** [comment] 2016-10-30 20:42
While I am also waiting for an update for macOS Sierra just like you guys, I tried to compile it myself from the source code. And then I used the complied binary to replace the old one in the app contents folder, and now it is working fine. It is probably just my luck, but you guys can have a try.

**Comment by alexkay** [comment] 2016-10-30 20:45
Dupe of #107

**Closed by alexkay** 2016-10-30 20:45 UTC

**Comment by matic13** [comment] 2016-11-12 11:00
Any news on an update?

**Comment by alexkay** [comment] 2016-12-27 23:33
Yes, see #107.
