### ISSUE TITLE
64-bit port?

### ISSUE THREAD

**Issue by KEXINO** [alexkay/spek#181] opened 2019-10-26 16:16 UTC
Any plans for a 64-bit port, to support OS X Catalina?

**Comment by dtrombly** [comment] 2019-10-31 21:24
This would be more than appreciated.

**Comment by gregforcey** [comment] 2019-11-04 18:03
The forked version works in Catalina for me: https://github.com/withmorten/spek-alternative/releases

**Comment by mattpopovich** [comment] 2020-08-24 06:02
This is a duplicate of #180 and #168. Recommending to close it.

**Comment by alexkay** [comment] 2023-02-06 21:52
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5

**Closed by alexkay** 2023-02-06 21:52 UTC
